version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://linkyun.co
        - VITE_WORKSPACE_CODE=vc
        - VITE_WORKSPACE_JOIN_CODE=thisiswhatwecall
        - VITE_SYSTEM_SERVICE_AGENT_CODE=vc-system
        - VITE_SYSTEM_AGENT_CODE=vc-vc
        - VITE_SYSTEM_ASSISTANT_AGENT_CODE=vc-assistant
        - VITE_SITE_THEME=vc
        - VITE_REGISTER_INVITATION_CODE=legalwise
        - VITE_TITLE=凌云智�本
    container_name: vc-frontend
    ports:
      - "81:80"
    restart: unless-stopped
