# 阶段1: 构建
FROM node:20-alpine AS builder

WORKDIR /app

# 复制依赖文件
COPY package*.json ./

# 安装依赖
RUN npm install && npm ci

# 复制源代码
COPY . .

# 构建参数（环境变量）
ARG VITE_API_BASE_URL
ARG VITE_WORKSPACE_CODE
ARG VITE_WORKSPACE_JOIN_CODE
ARG VITE_SYSTEM_SERVICE_AGENT_CODE
ARG VITE_SYSTEM_AGENT_CODE
ARG VITE_SYSTEM_ASSISTANT_AGENT_CODE
ARG VITE_SITE_THEME
ARG VITE_REGISTER_INVITATION_CODE
ARG VITE_TITLE

# 设置环境变量用于构建
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_WORKSPACE_CODE=$VITE_WORKSPACE_CODE
ENV VITE_WORKSPACE_JOIN_CODE=$VITE_WORKSPACE_JOIN_CODE
ENV VITE_SYSTEM_SERVICE_AGENT_CODE=$VITE_SYSTEM_SERVICE_AGENT_CODE
ENV VITE_SYSTEM_AGENT_CODE=$VITE_SYSTEM_AGENT_CODE
ENV VITE_SYSTEM_ASSISTANT_AGENT_CODE=$VITE_SYSTEM_ASSISTANT_AGENT_CODE
ENV VITE_SITE_THEME=$VITE_SITE_THEME
ENV VITE_REGISTER_INVITATION_CODE=$VITE_REGISTER_INVITATION_CODE
ENV VITE_TITLE=$VITE_TITLE

# 构建应用
RUN npm run build

# 阶段2: 生产环境
FROM nginx:alpine

# 复制自定义 nginx 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 从构建阶段复制构建产物
COPY --from=builder /app/dist /usr/share/nginx/html

# 暴露端口
EXPOSE 80 81

# 启动 nginx
CMD ["nginx", "-g", "daemon off;"]
